---
- name: Ensure MySQL users are present.
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    config_file: "{{ mysql_user_home}}/.my.cnf"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    append_privs: "{{ item.append_privs | default('no') }}"
  with_items: "{{ mysql_users }}"
  become: yes
  become_user: "{{ cmon_ssh_user }}"

